
server:
  port: 8084

spring:
  application:
    name: transaction
  datasource:
    url: jdbc:mysql://mysql-db:3306/banking_system   # MySQL container name
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka   # Eureka container name
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
