server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transactiondb
    username: root
    password: Akash@2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  kafka:
    bootstrap-servers: localhost:9092

jwt:
  secret: U2VjdXJlS2V5Rm9yQmFua2luZ0FwcFNob3VsZEJlQmFzZTY0
  expiration: 3600000