version: '3.8'

services:
  eureka-server:
    image: cloud:latest
    container_name: eureka-server
    ports:
      - "8763:8761"
    environment:
      # This explicitly sets the hostname for the Spring Boot application
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
    # Optional: If you need to expose this port to other containers in the same network
    # You can link services to this one by using the container_name