version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bank-net

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - bank-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    environment:
      KAFKA_KRAFT_CLUSTER_ID: kraft-cluster-id
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "${KAFKA_PORT}:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - bank-net

  eureka-server:
    build: ./cloud
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - bank-net

  auth-server:
    build: ./auth-server
    container_name: auth-server
    depends_on:
      - mysql
      - redis
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: ${AUTH_DB_URL}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: ${REDIS_PORT}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
    ports:
      - "8081:8081"
    networks:
      - bank-net

  account-service:
    build: ./account-service
    container_name: account-service
    depends_on:
      - mysql
      - kafka
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: ${ACCOUNT_DB_URL}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:${KAFKA_PORT}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
    ports:
      - "8082:8082"
    networks:
      - bank-net

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - mysql
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: ${USER_DB_URL}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
    ports:
      - "8083:8083"
    networks:
      - bank-net

  transaction-server:
    build: ./transaction-server
    container_name: transaction-server
    depends_on:
      - mysql
      - kafka
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: ${TRANSACTION_DB_URL}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:${KAFKA_PORT}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
    ports:
      - "8084:8084"
    networks:
      - bank-net

  notification-server:
    build: ./notification-server
    container_name: notification-server
    depends_on:
      - kafka
      - eureka-server
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:${KAFKA_PORT}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
    ports:
      - "8085:8085"
    networks:
      - bank-net

volumes:
  mysql_data:
  kafka_data:

networks:
  bank-net:
    driver: bridge
