server:
  port: 8081

spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://mysql-db:3306/banking_system   # Use service name from Docker Compose
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: kafka:9092               # Kafka container name
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  cache:
    type: redis
  data:
    redis:
      host: redis                                # Redis container name
      port: 6379                                 # default Redis port inside container
      password: LKIudJQ9HnyyOzJQZdBVf3BjDWQSHyac
      timeout: 3000

jwt:
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka   # Eureka container name
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true