version: '3.8'
services:

  mysql-loan:
    image: mysql:8
    container_name: mysql-loan
    environment:
      MYSQL_ROOT_PASSWORD: Akash@2003
      MYSQL_DATABASE: loan_db
    ports:
      - "3309:3306"
    volumes:
      - loan-mysql-data:/var/lib/mysql

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,EXTERNAL://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /tmp/kraft:/tmp/kraft-combined-logs

  loan-service:
    build: .
    container_name: loan-service
    depends_on:
      - kafka
      - mysql-loan
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-loan:3306/loan_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Akash@2003
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      JWT_SECRET: your-very-secret-key-of-256-bits-minimum
    ports:
      - "8086:8086"
    networks:
      - banking-net

volumes:
  loan-mysql-data:

networks:
  banking-net:
