
server:
  port: 8082

spring:
  application:
    name: user

  datasource:
    url: jdbc:mysql://mysql-db:3306/banking_system   # MySQL service name in Docker
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092               # Kafka container name
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cache:
    type: redis
  data:
    redis:
      host: redis                                # Redis container name
      port: 6379
      password: LKIudJQ9HnyyOzJQZdBVf3BjDWQSHyac
      timeout: 3000

jwt:
  public-key-location: jwt-secrets/public-key.pem
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka   # Eureka container name
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
