server:
  port: 8082

spring:
  application:
    name: user

  datasource:
    url: jdbc:mysql://localhost:3306/banking_system
    username: root
    password: Akash@2003

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cache:
    type: redis

  data:
    redis:
      host: redis-16748.c301.ap-south-1-1.ec2.redns.redis-cloud.com
      port: 16748
      password: LKIudJQ9HnyyOzJQZdBVf3BjDWQSHyac
      timeout: 3000
#      ssl: true

jwt:
  public-key-location: jwt-secrets/public-key.pem
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true