
server:
  port: 8085

spring:
  application:
    name: notification

  kafka:
    bootstrap-servers: kafka:9092              # Kafka container name
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: equinoxfinancebank@gmail.com
    password: gplfihhlusxhscpp               # Use env variable in Docker for security
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka   # Eureka container name
    fetch-registry: true
    register-with-eureka: true