name: Auto Merge Feature Branch

on:
  workflow_run:
    workflows: ["Maven Build & Test"]
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Merge branch into master
        run: |
          git fetch origin master
          git checkout master
          git merge --no-ff ${{ github.event.workflow_run.head_branch }}
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
