name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build auth-service Docker image
      run: docker build ./auth-server --file ./auth-server/Dockerfile --tag auth-service:$(date +%s)

    - name: Build eureka-server Docker image
      run: docker build ./eureka-server --file ./eureka-server/Dockerfile --tag eureka-server:$(date +%s)

    - name: Build notification-service Docker image
      run: docker build ./notification-service --file ./notification-service/Dockerfile --tag notification-service:$(date +%s)

    - name: Build account-service Docker image
      run: docker build ./account-service --file ./account-service/Dockerfile --tag account-service:$(date +%s)

    - name: Build user-service Docker image
      run: docker build ./user-service --file ./user-service/Dockerfile --tag user-service:$(date +%s)

    - name: Build transaction-service Docker image
      run: docker build ./transaction-service --file ./transaction-service/Dockerfile --tag transaction-service:$(date +%s)
